name: Konyaku

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - ".github/scripts/**"
      - "modules/**"
      - "script/**"
      - "preloadbin/**"
      - "webui/**"
      - "version"

# Allow only one concurrent build workflows
concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build Konyaku Tweaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2


      - name: Building WebRoots
        working-directory: ./webui
        run: |
          bun install
          bun run build
          cp -r ./dist/* ../modules/webroot

      - name: Compile Flashable Zip
        id: compileZip
        run: bash .github/scripts/compile_zip.sh

      - name: Unzip Package
        run: |
          unzip ${{ steps.compileZip.outputs.zipName }} -d extracted

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ steps.compileZip.outputs.zipName }}
          path: extracted/**
